### ISSUE TITLE
navigation.tabs per menù corti o con nomi brevi di pagine 

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/ods-mkdocs-material#9]
sul file `mkdocs.yml`
se scelgo di fare visualizzare la navigazione nella tab dell'header

![image](https://user-images.githubusercontent.com/3757525/138571420-58c7257d-69df-4706-ad3b-ed437c5724c2.png)

devo dare l'istruzione 
`    - navigation.tabs`
su `# Configuration`:

```
# Configuration
theme:
  name: material
  custom_dir: docs/overrides/
  static_templates:
    - 404.html
  language: it
  features:
    - navigation.top
    - navigation.instant
    - navigation.tabs
```

Ho notato che se scrivo nomi di pagine non brevi oppure ho 10-12-14-ecc pagine, vien troncato l'elenco del menù delle pagine.

https://regolamento-bilancio-democrazia-partecipata-sangiuseppejato.readthedocs.io/ è un esempio in cui non si può scegliere di far visualizzare il menù nella tab dell'header ma farlo visualizzare nella colonna laterale a sinistra della pagina.
![image](https://user-images.githubusercontent.com/3757525/138571595-e6bcf6c9-0fc7-4642-abcf-c389727bc431.png)

Per questo motivo immagino che per menù con nomi di pagine lunghi o menù con numerose pagine da far visualizzare, la scelta da fare sia di non inserire il `    - navigation.tabs`  nella sezione `# Configuration`

A  meno che non ci sia da inserire un istruzione in qualche file (?) per permettere al menù di andare a capo nello stesso header.
